#ifndef _KERN_ERRORS_H
#define _KERN_ERRORS_H

#include "kern_panic.h"

enum {
	KERN_ERROR_OUT_OF_ARENA = 1,
	KERN_ERROR_PDE_NOT_PRESENT,
	KERN_ERROR_PAGE_NOT_PRESENT,
	KERN_ERROR_TOO_SMALL_REGION,
	KERN_ERROR_PDPTE_NOT_PRESENT,
	KERN_ERROR_PML4E_NOT_PRESENT,
	KERN_ERROR_PAGE_ALREADY_PRESENT,
	KERN_ERROR_ADDR_NOT_PAGE_ALIGNED,
	KERN_ERROR_MISSING_AVAILABLE_MEMTYPE,
	KERN_ERROR_MISSING_BOOTLOADER_MEMTYPE,
	KERN_ERROR_MISSING_ACPI_RECLAIM_MEMTYPE,
	KERN_ERROR_INVALID_PD,
	KERN_ERROR_INVALID_PT,
	KERN_ERROR_INVALID_PDPT,
	KERN_ERROR_INVALID_PML4,
	KERN_ERROR_INVALID_MEMMAP,
	KERN_ERROR_INVALID_REGION,
	KERN_ERROR_INVALID_ARENA_SIZE,
	KERN_ERROR_INVALID_PERMISSION
};

#define RET_ERROR(_ret) (_ret != 0)

#define KERN_PANIC(_ret)\
	do {kern_panic(_ret, __LINE__);} while (0)

#define KERN_CRITICAL_ERROR(_ret, ...)\
	do {\
		/* TODO */\
		kern_panic(_ret, __LINE__);\
	} while (0)

#endif
